### ISSUE TITLE
Axis formating

### ISSUE THREAD

**Issue by PMassicotte** [hadley/svglite#49] opened 2015-12-14 09:42 UTC
I'm having some difference using `svg` vs `svglite` device when producing the following html file. On the second plot (using svglite) the lables are too close of the tick and we are missing the bottom line of the graphic box.

https://gist.github.com/PMassicotte/4eb1e09255ef2bdb39af

**Comment by hadley** [comment] 2016-02-02 15:10
Can you please provide a minimal reproducible example inline, including the images?

**Comment by PMassicotte** [comment] 2016-02-02 16:52
This should do it.

https://gist.github.com/PMassicotte/4eb1e09255ef2bdb39af#file-example-rmd

**Comment by hadley** [comment] 2016-02-02 17:42
Can you please make it inline, with proper markdown formatting?

**Comment by PMassicotte** [comment] 2016-02-03 08:58
```r
library(ggplot2)
theme_set(theme_bw())

x <- seq(0, 5, length.out = 100)
y <- df(x, 3, 230)

svg("plot_svg.svg", width = 5, height = 4)
qplot(x, y, geom = "line", xlab = "F value", ylab = "f(x)")
dev.off()

png::writePNG(rsvg::rsvg("plot_svg.svg"), "plot_svg.png")

svglite::svglite("plot_svglite.svg", width = 5, height = 4)
qplot(x, y, geom = "line", xlab = "F value", ylab = "f(x)")
dev.off()

png::writePNG(rsvg::rsvg("plot_svglite.svg"), "plot_svglite.png"))
```

![plot_svg](https://cloud.githubusercontent.com/assets/4519221/12777344/939277cc-ca5c-11e5-80fd-3a3c118bdf5c.png)

![plot_svglite](https://cloud.githubusercontent.com/assets/4519221/12777346/9a1601e0-ca5c-11e5-99dc-5ed532c7f7a8.png)

**Comment by hadley** [comment] 2016-02-03 15:19
Duplicate of #47

**Comment by hadley** [comment] 2016-02-03 15:20
And #48

**Closed by hadley** 2016-02-03 15:19 UTC
